app/routes/data_routes.py
import logging
from typing import Dict

from flask import Blueprint, Response, current_app, request
from src.distance_metrics import DTW, EMD, L1, L2, LCSS, DistanceMetric

from ..action_prediction import ActionRecognitionApp

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler()],
)

data_routes = Blueprint("data_routes", __name__)


@data_routes.route("/visualize_joints")
def visualize_joints():
    """Route to visualize joint series data."""

    return current_app.pose_estimation_app_instance.visualize_joints()


@data_routes.route("/visualize_angles")
def visualize_angles():
    """Route to visualize angle series data."""

    return current_app.pose_estimation_app_instance.visualize_angles()


@data_routes.route("/visualize_fourier")
def visualize_fourier():
    """Route to visualize Fourier series data."""

    return current_app.pose_estimation_app_instance.visualize_fourier()


@data_routes.route("/export_joints")
def export_joints():
    """Route to export joint data as Excel."""
    return current_app.pose_estimation_app_instance.export_joints()


@data_routes.route("/export_angles")
def export_angles():
    """Route to export angle data as Excel."""
    return current_app.pose_estimation_app_instance.export_angles()


@data_routes.route("/export_fourier_magnitude")
def export_fourier_magnitude():
    """Route to export Fourier data as Excel."""
    return current_app.pose_estimation_app_instance.export_fourier_magnitude()


@data_routes.route("/export_fourier_phase")
def export_fourier_phase():
    """Route to export Fourier data as Excel."""
    return current_app.pose_estimation_app_instance.export_fourier_phase()


@data_routes.route("/action_recognition", methods=["POST"])
def action_recognition():
    DISTANCE_METRICS: Dict[str, DistanceMetric] = {
        "l1": L1,
        "l2": L2,
        "dtw": DTW,
        "lcss": LCSS,
        "emd": EMD,
    }

    """Route to predict the bodyweight exercise."""
    model_type = str(request.form["model_type"])
    feature_type = str(request.form["feature_type"])

    action_recognition_app_instance = ActionRecognitionApp(
        model_name=f"UCF101_{model_type}_{feature_type}_model.pth"
    )

    current_app.action_recognition_app_instance = action_recognition_app_instance
    if model_type == "knn":
        k = int(request.form["k"])
        metric = str(request.form["metric"])
        metric = DISTANCE_METRICS[metric]
        weights = str(request.form["weights"])
        current_app.action_recognition_app_instance.model.k = k
        current_app.action_recognition_app_instance.model.feature_type = feature_type
        current_app.action_recognition_app_instance.model.metric = metric()
        current_app.action_recognition_app_instance.model.weights = weights

    action_recognition_app_instance = ActionRecognitionApp(
        model_name=f"UCF101_{model_type}_{feature_type}_model.pth"
    )
    current_app.action_recognition_app_instance = action_recognition_app_instance

    if feature_type == "joints":
        X = current_app.pose_estimation_app_instance.joint_series
    elif feature_type == "angles":
        X = current_app.pose_estimation_app_instance.angle_series
    elif feature_type == "fourier":
        X = current_app.pose_estimation_app_instance.fourier_series

    current_app.action_recognition_app_instance.predict(X)
    return current_app.action_recognition_app_instance.visualize_predictions()

app/routes/index_routes.py
from flask import Blueprint, Response, current_app, redirect, render_template, request, url_for

index_routes = Blueprint("index_routes", __name__)

import logging
import os
import shutil

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler()],
)


@index_routes.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        if current_app.pose_estimation_app_instance.pose_estimation_active:
            current_app.pose_estimation_app_instance.terminate_estimation()
        else:
            logging.info("Reading pose estimation parameter values")
            min_detection_confidence = float(request.form["min_detection_confidence"])
            min_tracking_confidence = float(request.form["min_tracking_confidence"])
            model_complexity = int(request.form["model_complexity"])
            skip_frame = int(request.form["skip_frame"])
            source_type = str(request.form["source_type"])

            if source_type == "upload":
                webcam = None
                upload = request.files["video_upload"]
                logging.info(
                    f"Reading video input parameters ({source_type=}, {upload.filename=})"
                )
                save_dir = os.path.join(current_app.root_path, "saved")
                if os.path.exists(save_dir):
                    shutil.rmtree(save_dir)
                os.makedirs(save_dir, exist_ok=True)
                path = os.path.join(save_dir, upload.filename)
                upload.save(path)
                logging.info(f"Saved file {upload.filename} to {save_dir}")

            elif source_type == "webcam":
                webcam = int(request.form["webcam"])
                path = None
                logging.info(f"Reading video input parameters ({source_type=}, {webcam=}")

            current_app.pose_estimation_app_instance.start_estimation(
                min_detection_confidence,
                min_tracking_confidence,
                model_complexity,
                path,
                webcam,
                skip_frame,
            )

    if current_app.pose_estimation_app_instance.pose_estimation_active:
        action_button_text = "END POSE ESTIMATION"
        process_button_disabled = "disabled"
    else:
        action_button_text = "START POSE ESTIMATION"
        process_button_disabled = (
            "disabled" if current_app.pose_estimation_app_instance.landmarks_series is None else ""
        )
    return render_template(
        "index.html",
        action_button_text=action_button_text,
        process_button_disabled=process_button_disabled,
    )


@index_routes.route("/terminate", methods=["POST"])
def terminate():
    """Route to terminate pose estimation and redirect back to the homepage."""
    current_app.pose_estimation_app_instance.terminate_estimation()
    return redirect(url_for("index"))


@index_routes.route("/process_data", methods=["GET"])
def process_data():
    """Route to process data and render data processing template."""
    current_app.pose_estimation_app_instance.process_data()
    return render_template("process_data.html")


@index_routes.route("/video_feed")
def video_feed():
    """Route to provide video feed with annotated frames."""

    return Response(
        current_app.pose_estimation_app_instance.generate_frames(),
        mimetype="multipart/x-mixed-replace; boundary=frame",
    )

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>daltunay/calivision</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>
    <!-- Page title -->
    <h1 class="page-title">Calivision: your calisthenics companion</h1>

    <!-- Main Form -->
    <form id="poseEstimationForm" method="POST" enctype="multipart/form-data"
        action="{{ url_for('index_routes.index') }}">
        <!-- Parameters Section -->
        <div class="section">
            <h2 class="section-title">Parameters</h2>
            <div class="content-container">
                <!-- Parameter section for minimum detection confidence -->
                <div class="parameter-section">
                    <label for="min_detection_confidence"><code>min_detection_confidence:</code></label>
                    <input class="slider" type="range" id="min_detection_confidence" name="min_detection_confidence"
                        min="0" max="1" step="0.05" value="0.75" onchange="updateMinDetectionConfidence(this.value)">
                    <span id="min_detection_value"><code>0.75</code></span>
                    <div class="parameter-tooltip">The minimum confidence score for the pose detection to be considered
                        successful. </div>
                </div>

                <!-- Parameter section for minimum tracking confidence -->
                <div class="parameter-section">
                    <label for="min_tracking_confidence"><code>min_tracking_confidence:</code></label>
                    <input class="slider" type="range" id="min_tracking_confidence" name="min_tracking_confidence"
                        min="0" max="1" step="0.05" value="0.75" onchange="updateMinTrackingConfidence(this.value)">
                    <span id="min_tracking_value"><code>0.75</code></span>
                    <div class="parameter-tooltip">The minimum confidence score for the pose tracking to be considered
                        successful.</div>
                </div>

                <!-- Parameter section for model complexity -->
                <div class="parameter-section">
                    <label for="model_complexity"><code>model_complexity:</code></label>
                    <select id="model_complexity" name="model_complexity">
                        <option value=0>lite</option>
                        <option value=1 selected>full</option>
                        <option value=2>heavy</option>
                    </select>
                    <div class="parameter-tooltip">Complexity of the pose landmark model.<br>Landmark accuracy as well
                        as inference latency generally go up with the model complexity.</div>
                </div>

                <!-- Parameter section for skip frame -->
                <div class="parameter-section">
                    <label for="skip_frame"><code>skip_frame:</code></label>
                    <input type="number" id="skip_frame" name="skip_frame" min="0" step="1" value="0"
                        style="width: 35px;">
                    <div class="parameter-tooltip">Number of frames to skip between two consecutive processed frames.
                    </div>
                </div>

                <!-- Video Source Section -->
                <div class="section">
                    <h2 class="section-title">Video Source</h2>
                    <div class="content-container">
                        <!-- Choose video source -->
                        <div class="parameter-section">
                            <label>Choose your video source:</label>
                            <input type="radio" name="source_type" value="webcam" onchange="handleSourceChange()">
                            <label>Webcam</label>
                            <input type="radio" name="source_type" value="upload" onchange="handleSourceChange()">
                            <label>Upload</label>
                            <div class="parameter-tooltip">Whether to use the device webcam or an uploaded video for the
                                pose estimation.</div>
                        </div>

                        <!-- Webcam Input -->
                        <div class="parameter-section" id="webcam-container">
                            <label><code>webcam_input:</code></label>
                            <input type="radio" name="webcam" value="0">
                            <label>0</label>
                            <input type="radio" name="webcam" value="1">
                            <label>1</label>
                            <div class="parameter-tooltip">Webcam to use for the pose estimation.<br>The choice 1 only
                                works if you have 2 webcams on your device.</div>
                        </div>

                        <!-- Video Input -->
                        <div class="parameter-section" id="upload-container">
                            <label><code>video_input:</code></label>
                            <input type="file" name="video_upload" accept="video/*">
                            <div class="parameter-tooltip">The input to be used for the pose estimation. Video format
                                only.</div>
                        </div>
                    </div>
                </div>

                <!-- Action and Process Button Section -->
                <div class="section">
                    <h2 class="section-title">Pose Estimation</h2>
                    <div class="vertical-button-group">
                        <!-- Action button -->
                        <input class="button-disabled" type="submit" value="{{ action_button_text }}" id="actionButton"
                            disabled>
                    </div>
    </form>
    <!-- Form for processing data -->
    <form method="GET" action="{{ url_for('index_routes.process_data') }}">
        <!-- Process data button -->
        <input class="button{{ ' button-disabled' if process_button_disabled else '' }}" type="submit"
            value="PROCESS DATA" {{ process_button_disabled }}>
    </form>
    </div>

    <!-- Display Video Feed -->
    <div class="video-feed-container">
        <img src="{{ url_for('index_routes.video_feed') }}" alt="Video Feed" style="max-width: 100%;">
    </div>

    <!-- Social media -->
    <div class="social-links-container">
        <a class="social-link" href="https://github.com/daltunay/calivision/" target="_blank">
            <img src="{{ url_for('static', filename='img/github_logo.png') }}" alt="GitHub">
        </a>
        <a class="social-link" href="https://www.linkedin.com/in/daltunay/" target="_blank">
            <img src="{{ url_for('static', filename='img/linkedin_logo.png') }}" alt="LinkedIn">
        </a>
    </div>

    <!-- Collapsible Panel -->
    <div class="collapsible-panel">
        <div class="collapsible-header" onclick="toggleCollapsiblePanel()">Mediapipe landmarks</div>
        <div class="collapsible-content">
            <img src="{{ url_for('static', filename='img/mediapipe_landmarks.png') }}"
                alt="Mediapipe Landmarks" style="max-width: 100%;">
        </div>
    </div>


    <!-- JavaScript -->
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>

</body>

</html>

app/templates/process_data.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Processed Data</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>
    <h1 class="page-title">Explore Data</h1>
    <div class="content-container">
        <div class="columns-container">
            <div class="column">
                <div class="section">
                    <h2 class="section-title">Extracted joint coordinates</h2>
                    <div class="vertical-button-group">
                        <a href="{{ url_for('data_routes.visualize_joints') }}" class="button">See 1 plot</a>
                        <a href="{{ url_for('data_routes.export_joints') }}" class="button">Export coordinates</a>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="section">
                    <h2 class="section-title">Computed body angles</h2>
                    <div class="vertical-button-group">
                        <a href="{{ url_for('data_routes.visualize_angles') }}" class="button">See 2 plots</a>
                        <a href="{{ url_for('data_routes.export_angles') }}" class="button">Export angles</a>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="section">
                    <h2 class="section-title">Angles Fourier transform</h2>
                    <div class="vertical-button-group">
                        <a href="{{ url_for('data_routes.visualize_fourier') }}" class="button">See 2 plots</a>
                        <div class="horizontal-button-group">
                            <a href="{{ url_for('data_routes.export_fourier_magnitude') }}" class="button">Export
                                magnitudes</a>
                            <a href="{{ url_for('data_routes.export_fourier_phase') }}" class="button">Export
                                phases</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="back-link-container">
            <a href="{{ url_for('index_routes.index') }}" class="back-link">Back</a>
        </div>
    </div>

    <!-- Predictions -->
    <div class="section">
        <div class="content-container">
            <h1 class="page-title">Action recognition</h2>
                <p>Classifying video among bodyweight exercises</p>
                <form action="{{ url_for('data_routes.action_recognition') }}" method="post">
                    <!-- Parameter section for model type -->
                    <div class="parameter-section">
                        <label for="model_type"><code>model_type:</code></label>
                        <select id="model_type" name="model_type" onchange="updateParameters()">
                            <option value="knn" selected>knn</option>
                            <option value="lstm">lstm</option>
                        </select>
                        <div class="parameter-tooltip">The type of model to use for the classification<br>(either K-nearest
                            neighbors or Long Short Term Memory classifier)</div>
                    </div>

                    <!-- Parameter section for k -->
                    <div class="parameter-section">
                        <label for="k"><code>k:</code></label>
                        <input type="number" id="k" name="k" min=1 step=2 value=5 style="width: 35px;">
                        <div class="parameter-tooltip">The value of k to use for the kNN classifier.</div>
                    </div>

                    <!-- Parameter section for feature type -->
                    <div class="parameter-section">
                        <label for="feature_type"><code>feature_type:</code></label>
                        <select id="feature_type" name="feature_type" onchange="updateMetrics()">
                            <option value="joints">joints</option>
                            <option value="angles">angles</option>
                            <option value="fourier" selected>fourier</option>
                        </select>
                        <div class="parameter-tooltip">The type of features to use for the classification (cf. above
                            section [Explore Data])</div>
                    </div>

                    <!-- Parameter section for metric -->
                    <div class="parameter-section">
                        <label for="metric"><code>metric:</code></label>
                        <select id="metric" name="metric">
                            <option value="l1" disabled>l1</option>
                            <option value="l2" disabled>l2</option>
                            <option value="dtw" disabled>dtw</option>
                            <option value="lcss" disabled>lcss</option>
                            <option value="emd" selected>emd</option>
                        </select>
                        <div class="parameter-tooltip">The distance metric to use for the kNN classifier.</div>
                    </div>

                    <!-- Parameter section for weights -->
                    <div class="parameter-section">
                        <label for="weights"><code>weights:</code></label>
                        <select id="weights" name="weights">
                            <option value="uniform" selected>uniform</option>
                            <option value="distances">distances</option>
                        </select>
                        <div class="parameter-tooltip">Whether to use a uniform weighting, or an inverse-distance
                            weighting.</div>
                    </div>

                    <!-- Predict button -->
                    <div class="vertical-button-group">
                        <button type="submit" class="button">PREDICT</button>
                    </div>
                </form>
        </div>

    </div>
    <!-- Social media -->
    <div class="social-links-container">
        <a class="social-link" href="https://github.com/daltunay/calivision/" target="_blank">
            <img src="{{ url_for('static', filename='img/github_logo.png') }}" alt="GitHub">
        </a>
        <a class="social-link" href="https://www.linkedin.com/in/daltunay/" target="_blank">
            <img src="{{ url_for('static', filename='img/linkedin_logo.png') }}" alt="LinkedIn">
        </a>
    </div>

    <!-- JavaScript -->
    <script src="{{ url_for('static', filename='js/process_data.js') }}">
        // Call the updateMetrics() function on page load
        window.addEventListener('load', function () {
            updateMetrics();
        });
    </script>
</body>

</html>

app/templates/visualize_angles.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Angle Visualizations</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>
    <h1 class="page-title">Explore Processed Data</h1>

    <h2 class="section-title">Angle Evolution</h2>
    <div class="plot-container">
        <div class="plot-description">
            <p>This is a plot of all the angle time series : each line corresponds to a set of 3 joints (only visible
                angles are shown on the graph).<br>These were
                computed using the 3D joint coordinates.</p>
        </div>
        <div id="angle-evolution-plot" class="plot"></div>
    </div>

    <h2 class="section-title">Angle Heatmap</h2>
    <div class="plot-container">
        <div class="plot-description">
            <p>This is a heatmap of all the angle values over time (only visible
                angles are shown on the graph). The brighter the color, the higher the anglue value.
            </p>
        </div>
        <div id="angle-heatmap-plot" class="plot"></div>
    </div>

    <div class="back-link-container">
        <a href="{{ url_for('index_routes.process_data') }}" class="back-link">Back</a>
        <a href="{{ url_for('index_routes.index') }}" class="back-link">Home</a>
    </div>

    <script>
        const angleEvolutionData = {{ angle_evolution_plot| safe }};
        Plotly.newPlot('angle-evolution-plot', angleEvolutionData);

        const angleHeatmapData = {{ angle_heatmap_plot| safe }};
        Plotly.newPlot('angle-heatmap-plot', angleHeatmapData);
    </script>
</body>

</html>

app/templates/visualize_fourier.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fourier Visualizations</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>
    <h1 class="page-title">Fourier Visualizations</h1>

    <h2 class="section-title">Magnitude Plot</h2>
    <div class="plot-container">
        <div class="plot-description">
            <p>This is the magnitude spectrum of the Fast Fourier Transform applied to the angle time series. For each
                angle (set of 3 joints), each time frequency has its magnitude value.<br>Only angles which were visible
                at least 50% of the time are shown.</p>
        </div>
        <div id="fourier-magnitude-plot" class="plot"></div>
    </div>

    <h2 class="section-title">Phase Plot</h2>
    <div class="plot-container">
        <div class="plot-description">
            <p>This is the phase spectrum of the Fast Fourier Transform applied to the angle time series. For each angle
                (set of 3 joints), each time frequency has its phase value.<br>Only angles which were visible at least
                50% of the time are shown.</p>
        </div>
        <div id="fourier-phase-plot" class="plot"></div>
    </div>

    <div class="back-link-container">
        <a href="{{ url_for('index_routes.process_data') }}" class="back-link">Back</a>
        <a href="{{ url_for('index_routes.index') }}" class="back-link">Home</a>
    </div>

    <script>
        const fourierMagnitudeData = {{ fourier_magnitude_plot| safe }};
        Plotly.newPlot('fourier-magnitude-plot', fourierMagnitudeData);

        const fourierPhaseData = {{ fourier_phase_plot| safe }};
        Plotly.newPlot('fourier-phase-plot', fourierPhaseData);
    </script>
</body>

</html>

app/templates/visualize_joints.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Joint Series Visualization</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>
    <h1 class="page-title">Joint Series Visualization</h1>

    <div class="plot-container">
        <div class="plot-description">
            <p>This is a 3D interactive plot displaying visible body joints. Use your cursor to move around the body,
                and use the bottom slider to select your desired timestamp.<br>Only visible joints are shown.</p>
        </div>
        <div id="joint-visualization" class="plot"></div>
    </div>

    <div class="back-link-container">
        <a href="{{ url_for('index_routes.process_data') }}" class="back-link">Back</a>
        <a href="{{ url_for('index_routes.index') }}" class="back-link">Home</a>
    </div>

    <script>
        const jointData = {{ joint_series_plot| safe }};
        Plotly.newPlot('joint-visualization', jointData);
    </script>
</body>

</html>

app/templates/visualize_predictions.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualize Predictions</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>
    <h1 class="page-title">Visualize Predictions</h1>
    <div class="content-container">
        <div class="columns-container">
            <div class="column">
                <div class="section">
                    <h2 class="section-title">Predicted Classes and Probabilities</h2>
                    <div class="plot-container">
                        <ul class="prediction-list">
                            {% for class_name, probability in predictions.items() %}
                            <li>
                                <span class="class-name">{{ class_name }}</span>
                                <span class="probability-bar" style="width: {{ probability * 100 }}%"></span>
                                <span class="probability">{{ '%.2f'|format(probability) }}</span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="back-link-container">
            <a href="{{ url_for('index_routes.process_data') }}" class="back-link">Back</a>
            <a href="{{ url_for('index_routes.index') }}" class="back-link">Home</a>
        </div>
    </div>
    <!-- Social media -->
    <div class="social-links-container">
        <a class="social-link" href="https://github.com/daltunay/calivision/" target="_blank">
            <img src="{{ url_for('static', filename='img/github_logo.png') }}" alt="GitHub">
        </a>
        <a class="social-link" href="https://www.linkedin.com/in/daltunay/" target="_blank">
            <img src="{{ url_for('static', filename='img/linkedin_logo.png') }}" alt="LinkedIn">
        </a>
    </div>
</body>

</html>